// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjmo1s35H00MKkRKtqWRhSNYUH3raDjA8',
    appId: '1:785447164436:web:00dae02cc560b65a6aa501',
    messagingSenderId: '785447164436',
    projectId: 'emosphere-9e78f',
    authDomain: 'emosphere-9e78f.firebaseapp.com',
    storageBucket: 'emosphere-9e78f.appspot.com',
    measurementId: 'G-2EN2F465MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEM_vfGcW5HnomVff2xmw4I8SPRYqKSDo',
    appId: '1:785447164436:android:7e7ee63f6d304d6a6aa501',
    messagingSenderId: '785447164436',
    projectId: 'emosphere-9e78f',
    storageBucket: 'emosphere-9e78f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCntXm6T_VZwQXhROVQEZkuXAVnWRYQh-k',
    appId: '1:785447164436:ios:9c82c0d40a51a04f6aa501',
    messagingSenderId: '785447164436',
    projectId: 'emosphere-9e78f',
    storageBucket: 'emosphere-9e78f.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCntXm6T_VZwQXhROVQEZkuXAVnWRYQh-k',
    appId: '1:785447164436:ios:7542e2a881b50d4f6aa501',
    messagingSenderId: '785447164436',
    projectId: 'emosphere-9e78f',
    storageBucket: 'emosphere-9e78f.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
